### PR TITLE
Provide example secret configuration files

### PR DESCRIPTION
**Pull request by emk**
Based on discussions earlier this week, I think conductor needs to know about secrets and how containers access them. If it doesn't, people are going to be tempted to put secrets into version control, and it will be much more cumbersome to develop locally.

After thinking about this a bunch today, this is how I visualize this working.  We would have two backends:

1. Secrets loaded from a `config/secrets.yml` file and injected into an
   appropriate container.
2. Secrets loaded from vault.  This would essentially be a
   re-implementation of our `add-vault-tokens` gem (which is super tiny)
   in Rust, with full conductor integration and a few wishlist features
   that will simplify administration and allow us to use it for other
   projects.

@seamusabshere, @dkastner Thoughts on this design? Ultimately, we wouldn't include both these files in the standard `new` generator, but would move one or both to a separate generator.

Probably we'll implement these as a "plugins" pass that gets to transform a `dc::File` before it gets output. We'll probably add other similar plugins.

### CODE REVIEW

**Comment by dkastner** [comment]
I really like this approach, very rails-like yet very 12-factor :)

**Comment by seamusabshere** [comment]
@emk to make sure i understand, secrets.yml mirrors the structure of the pods/ directory? and basically mixes in secrets as env vars?

**Comment by emk** [comment]
@seamusabshere Yup. It looks as much like `pods` as possible. I thought about having lots of little `$SOMETHING.secrets.env` files scattered throughout the `pods` directory, but since none of this is supposed to go in version control, I decided it was better to put it all in a single, easily copied file.

**Comment by seamusabshere** [comment]
@emk this is perfect

**Comment by emk** [comment]
OK, it looks like vault has uncovered several issues:

- [ ] We need to only output yml files for the current override, not all overrides.
- [ ] We need some way to only run a plugin for specific overrides, at least for vault.
- [ ] We need to split out the secret-related generators.

**Comment by emk** [comment]
This patch also introduces our plugin system, which will eventually be the heart of almost everything we do. So if you only have time to review some of, try the [plugins directory](https://github.com/faradayio/conductor/tree/secret_handling/src/plugins).

Yes, I wrote all this since last Friday morning. 😕

I'm going to go ahead and merge it since nobody is available for review, but I'll look at reviews later.

**Pull request merged**
